### ISSUE TITLE
Question: Scaling the nodes

### ISSUE THREAD

**Issue by SG1990** [High-Core/WPFSamples#1]
Hi! These are indeed fabulous samples. But how would you go about enabling the user to resize the nodes in the Node Editor / House Plan? I've been trying to combine your project (In a slightly modified form) with another that allows the user to resize objects by creating a frame of Thumbs. Up until now, I've had little success. If you could possibly take a look at my question at StackOverflow and give me a hint, I would be eternally indebted to you. Here are the details:
http://stackoverflow.com/q/24899172/3828965

Regards,
Alex

**Comment by fberasategui** [comment]
Hi. Do you still need help with this? I'm sorry I haven't been active on GitHub for a very long time.
